name: Spark Excel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:
    

jobs:
  build:
    strategy:
      matrix:
        sparkVersion: [ 3.0.1, 3.0.2, 3.1.1, 3.1.2 ]
  
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout with LFS
      uses: actions/checkout@v2
      with:
        lfs: true
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    
    - name: Run tests and produce coverage
      run: sbt -DsparkVersion="${{matrix.sparkVersion}}" clean coverageOn test coverageReport
